/**
 * WGate backend — PostgreSQL edition, schema-per-society multi-tenancy.
 *
 * Architecture:
 *   - A shared/public schema holds: `societies` (the directory of all
 *     societies), `superadmins` (accounts not tied to any society), and
 *     `sessions` (routes each login to the right society's schema, or to
 *     the superadmin table when society_id is null).
 *   - Each society gets its OWN Postgres schema (e.g. society_a1b2c3...)
 *     containing its own `entity_records` table — User, Visitor,
 *     ServiceTicket, MaintenanceBill, Notice, SocietySettings all live
 *     there, fully separate from every other society's data. No shared
 *     table, no society_id filter needed to keep them apart — the schema
 *     boundary does that structurally.
 *
 * Works identically whether DATABASE_URL points at:
 *   - a Neon free Postgres project (recommended — no expiration), or
 *   - Render's own free Postgres (expires 30 days after creation), or
 *   - any other Postgres instance.
 *
 * Start it with `npm run dev` (starts this + Vite together) or `npm run dev:api`.
 */
import { config as loadEnv } from 'dotenv';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import express from 'express';
import cors from 'cors';
import crypto from 'node:crypto';
import pg from 'pg';

// dotenv's default `dotenv/config` import only reads a file named
// `.env`. This project (and the rest of the Vite tooling) uses
// `.env.local`, so load that explicitly. Falls back silently if the
// file doesn't exist (e.g. when real env vars are injected by a host
// like Render instead).
const __dirname = path.dirname(fileURLToPath(import.meta.url));
loadEnv({ path: path.resolve(__dirname, '..', '.env.local') });

const PORT = Number(process.env.WGATE_API_PORT || process.env.PORT || 4400);
// 0.0.0.0 works for local dev (still reachable via localhost) and is
// required by most hosting platforms (Render, etc.) which need the
// server to bind all interfaces, not just the loopback address.
const HOST = process.env.WGATE_API_HOST || '0.0.0.0';
const SESSION_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days
const DEFAULT_INVITE_PASSWORD = 'welcome123';

const ENTITIES = ['User', 'SocietySettings', 'Visitor', 'ServiceTicket', 'MaintenanceBill', 'Notice'];

const ENTITY_DEFAULTS = {
  User: { role: 'tenant' },
  Visitor: { status: 'pending' },
  ServiceTicket: { priority: 'medium', status: 'open' },
  MaintenanceBill: { status: 'pending' },
  Notice: { type: 'announcement', is_pinned: false },
};

const ROLES = ['admin', 'tenant', 'owner', 'guard'];
const SELF_EDITABLE_FIELDS = ['full_name', 'phone', 'flat_number'];

/* ------------------------------------------------------------------ */
/* Password + token helpers (node:crypto only)                        */
/* ------------------------------------------------------------------ */

function hashPassword(password) {
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(String(password), salt, 64).toString('hex');
  return `scrypt$${salt}$${hash}`;
}

function verifyPassword(password, stored) {
  if (!stored || typeof stored !== 'string') return false;
  const [scheme, salt, hash] = stored.split('$');
  if (scheme !== 'scrypt' || !salt || !hash) return false;
  const candidate = crypto.scryptSync(String(password), salt, 64);
  const expected = Buffer.from(hash, 'hex');
  return candidate.length === expected.length && crypto.timingSafeEqual(candidate, expected);
}

function generateTempPassword() {
  return `Temp-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
}

const sha256 = (value) => crypto.createHash('sha256').update(value).digest('hex');
const newId = () => crypto.randomUUID();
const nowIso = () => new Date().toISOString();
const normEmail = (email) => String(email || '').trim().toLowerCase();

/* ------------------------------------------------------------------ */
/* Postgres connection                                                */
/* ------------------------------------------------------------------ */

if (!process.env.DATABASE_URL) {
  console.error(
    '[wgate-api] DATABASE_URL is not set. Point it at a Postgres connection string ' +
    '(e.g. a Neon project) — see server/README-local.md.'
  );
  process.exit(1);
}

const isLocalDb = /localhost|127\.0\.0\.1/.test(process.env.DATABASE_URL);
const pool = new pg.Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: isLocalDb ? false : { rejectUnauthorized: false },
});

pool.on('error', (err) => {
  console.error('[wgate-api] Unexpected Postgres error on idle client:', err.message);
});

/* ------------------------------------------------------------------ */
/* Schema-per-society helpers                                         */
/* ------------------------------------------------------------------ */

// Society ids are always crypto.randomUUID() generated by this server,
// so this pattern is a defensive check, not user-facing validation.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function schemaNameForSociety(societyId) {
  if (typeof societyId !== 'string' || !UUID_RE.test(societyId)) {
    throw Object.assign(new Error('Invalid society id'), { status: 400 });
  }
  return `society_${societyId.replace(/-/g, '')}`;
}

async function ensureSocietySchema(schemaName) {
  await pool.query(`CREATE SCHEMA IF NOT EXISTS "${schemaName}"`);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS "${schemaName}".entity_records (
      entity TEXT NOT NULL,
      id UUID NOT NULL,
      data JSONB NOT NULL,
      created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_date TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (entity, id)
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_entity_records_entity ON "${schemaName}".entity_records(entity);`);
}

/* ------------------------------------------------------------------ */
/* Shared (public schema) tables: societies, superadmins, sessions    */
/* ------------------------------------------------------------------ */

async function initSchema() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS societies (
      id UUID PRIMARY KEY,
      name TEXT NOT NULL,
      city TEXT NOT NULL DEFAULT '',
      address TEXT NOT NULL DEFAULT '',
      total_flats INT,
      schema_name TEXT NOT NULL UNIQUE,
      created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_date TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS superadmins (
      id UUID PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      full_name TEXT NOT NULL,
      must_change_password BOOLEAN NOT NULL DEFAULT true,
      disabled BOOLEAN NOT NULL DEFAULT false,
      created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_date TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS sessions (
      id UUID PRIMARY KEY,
      user_id UUID NOT NULL,
      society_id UUID,
      token_hash TEXT NOT NULL UNIQUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      expires_at TIMESTAMPTZ NOT NULL
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash);`);
}

function rowToSociety(row) {
  return {
    id: row.id,
    name: row.name,
    city: row.city || '',
    address: row.address || '',
    total_flats: row.total_flats,
    created_date: row.created_date instanceof Date ? row.created_date.toISOString() : row.created_date,
    updated_date: row.updated_date instanceof Date ? row.updated_date.toISOString() : row.updated_date,
  };
}

async function listSocieties() {
  const { rows } = await pool.query('SELECT * FROM societies ORDER BY name');
  return rows.map(rowToSociety);
}

async function getSocietyById(id) {
  if (!id || typeof id !== 'string') return null;
  const { rows } = await pool.query('SELECT * FROM societies WHERE id = $1', [id]);
  return rows[0] ? rowToSociety(rows[0]) : null;
}

async function getSocietySchemaName(id) {
  const { rows } = await pool.query('SELECT schema_name FROM societies WHERE id = $1', [id]);
  return rows[0]?.schema_name || null;
}

async function createSocietyRecord({ name, city, address, total_flats }) {
  const id = newId();
  const schemaName = schemaNameForSociety(id);
  await pool.query(
    `INSERT INTO societies (id, name, city, address, total_flats, schema_name) VALUES ($1,$2,$3,$4,$5,$6)`,
    [id, name, city || '', address || '', total_flats ?? null, schemaName]
  );
  await ensureSocietySchema(schemaName);
  return getSocietyById(id);
}

async function updateSocietyRecord(id, patch) {
  const existing = await getSocietyById(id);
  if (!existing) return null;
  const merged = { ...existing, ...patch };
  await pool.query(
    `UPDATE societies SET name=$1, city=$2, address=$3, total_flats=$4, updated_date=now() WHERE id=$5`,
    [merged.name, merged.city, merged.address, merged.total_flats, id]
  );
  return getSocietyById(id);
}

async function deleteSocietyRecord(id) {
  const schemaName = await getSocietySchemaName(id);
  if (!schemaName) return false;
  await pool.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`);
  await pool.query('DELETE FROM societies WHERE id = $1', [id]);
  return true;
}

/* ------------------------------------------------------------------ */
/* Per-society entity data access (schema-qualified)                  */
/* ------------------------------------------------------------------ */

async function listEntity(schemaName, entity) {
  const { rows } = await pool.query(`SELECT data FROM "${schemaName}".entity_records WHERE entity = $1`, [entity]);
  return rows.map((r) => r.data);
}

async function countEntity(schemaName, entity) {
  const { rows } = await pool.query(`SELECT COUNT(*)::int AS n FROM "${schemaName}".entity_records WHERE entity = $1`, [entity]);
  return rows[0].n;
}

async function getEntityRecord(schemaName, entity, id) {
  const { rows } = await pool.query(`SELECT data FROM "${schemaName}".entity_records WHERE entity = $1 AND id = $2`, [entity, id]);
  return rows[0]?.data || null;
}

async function insertEntityRecord(schemaName, entity, record) {
  await pool.query(
    `INSERT INTO "${schemaName}".entity_records (entity, id, data, created_date, updated_date) VALUES ($1,$2,$3,$4,$5)`,
    [entity, record.id, record, record.created_date, record.updated_date]
  );
  return record;
}

async function updateEntityRecord(schemaName, entity, id, record) {
  await pool.query(
    `UPDATE "${schemaName}".entity_records SET data=$1, updated_date=$2 WHERE entity=$3 AND id=$4`,
    [record, record.updated_date, entity, id]
  );
  return record;
}

async function deleteEntityRecord(schemaName, entity, id) {
  await pool.query(`DELETE FROM "${schemaName}".entity_records WHERE entity=$1 AND id=$2`, [entity, id]);
}

async function findUserByEmail(schemaName, email) {
  const { rows } = await pool.query(
    `SELECT data FROM "${schemaName}".entity_records WHERE entity = 'User' AND data->>'email' = $1`,
    [normEmail(email)]
  );
  return rows[0]?.data || null;
}

/* ------------------------------------------------------------------ */
/* Seed data (only on a fresh database)                                */
/* ------------------------------------------------------------------ */

function baseRecord(extra = {}) {
  const ts = nowIso();
  return {
    id: newId(),
    created_date: ts,
    updated_date: ts,
    created_by: 'admin@wgate.local',
    created_by_id: null,
    is_sample: false,
    ...extra,
  };
}

async function seedIfEmpty() {
  const { rows: societyCountRows } = await pool.query('SELECT COUNT(*)::int AS n FROM societies');
  if (societyCountRows[0].n === 0) {
    const society = await createSocietyRecord({
      name: 'Green Valley Residency',
      address: '12, Lake View Road',
      city: 'Bengaluru',
      total_flats: 120,
    });
    const schemaName = await getSocietySchemaName(society.id);

    const mkUser = (email, password, full_name, role, flat_number, phone) =>
      baseRecord({
        email,
        password_hash: hashPassword(password),
        full_name,
        role,
        flat_number,
        phone,
        society_id: society.id,
        society_name: society.name,
        disabled: false,
        is_verified: true,
      });

    const admin = mkUser('admin@wgate.local', 'admin123', 'WGate Admin', 'admin', 'Office', '9000000001');
    const guard = mkUser('guard@wgate.local', 'guard123', 'Gate Guard', 'guard', '', '9000000002');
    const tenant = mkUser('tenant@wgate.local', 'tenant123', 'Asha Tenant', 'tenant', 'A-101', '9000000003');
    const owner = mkUser('owner@wgate.local', 'owner123', 'Om Owner', 'owner', 'B-202', '9000000004');
    for (const u of [admin, guard, tenant, owner]) await insertEntityRecord(schemaName, 'User', u);

    const hoursAgo = (h) => new Date(Date.now() - h * 3600 * 1000).toISOString();

    await insertEntityRecord(schemaName, 'Visitor', baseRecord({
      visitor_name: 'Rahul Sharma',
      visitor_phone: '9876543210',
      purpose: 'guest',
      flat_number: 'A-101',
      resident_email: tenant.email,
      status: 'pending',
      vehicle_number: 'KA01AB1234',
      check_in_time: hoursAgo(1),
    }));
    await insertEntityRecord(schemaName, 'Visitor', baseRecord({
      visitor_name: 'Swiggy Delivery',
      visitor_phone: '9123456780',
      purpose: 'delivery',
      flat_number: 'B-202',
      resident_email: owner.email,
      status: 'approved',
      check_in_time: hoursAgo(3),
    }));

    await insertEntityRecord(schemaName, 'ServiceTicket', baseRecord({
      title: 'Kitchen tap leaking',
      description: 'The kitchen tap has been dripping since yesterday.',
      category: 'plumber',
      priority: 'medium',
      status: 'open',
      flat_number: 'A-101',
      resident_email: tenant.email,
    }));
    await insertEntityRecord(schemaName, 'ServiceTicket', baseRecord({
      title: 'Corridor light not working',
      description: 'Second floor corridor light is out.',
      category: 'electrician',
      priority: 'low',
      status: 'in_progress',
      flat_number: 'B-202',
      resident_email: owner.email,
      assigned_to: 'Society electrician',
    }));

    await insertEntityRecord(schemaName, 'Notice', baseRecord({
      title: 'Welcome to WGate',
      content: 'This is your WGate environment, with each society kept in its own database schema. Post notices, track visitors and manage service tickets.',
      type: 'announcement',
      society_id: society.id,
      society_name: society.name,
      posted_by: admin.full_name,
      is_pinned: true,
    }));

    const month = new Date().toISOString().slice(0, 7);
    await insertEntityRecord(schemaName, 'MaintenanceBill', baseRecord({
      flat_number: 'A-101',
      resident_email: tenant.email,
      resident_name: tenant.full_name,
      amount: 2500,
      month,
      month_label: new Date().toLocaleString('en-US', { month: 'long', year: 'numeric' }),
      due_date: `${month}-10`,
      status: 'pending',
    }));

    console.log('[wgate-api] Seeded development data with local accounts (see server/README-local.md).');
  }

  const { rows: saCountRows } = await pool.query('SELECT COUNT(*)::int AS n FROM superadmins');
  if (saCountRows[0].n === 0) {
    await pool.query(
      `INSERT INTO superadmins (id, email, password_hash, full_name, must_change_password) VALUES ($1,$2,$3,$4,true)`,
      [newId(), 'superadmin@wgate.local', hashPassword('super123'), 'Super Admin']
    );
    console.log('[wgate-api] Seeded superadmin account.');
  }
}

/* ------------------------------------------------------------------ */
/* Auth: sessions, superadmin table, login resolution                 */
/* ------------------------------------------------------------------ */

function publicUser(user) {
  if (!user) return null;
  // eslint-disable-next-line no-unused-vars
  const { password_hash, ...rest } = user;
  return {
    ...rest,
    // Default to true for any record that predates this field — forces a
    // password change rather than silently trusting an old password.
    must_change_password: user.must_change_password !== false,
  };
}

function superadminRowToUser(row) {
  return {
    id: row.id,
    email: row.email,
    password_hash: row.password_hash,
    full_name: row.full_name,
    role: 'superadmin',
    society_id: null,
    society_name: '',
    disabled: row.disabled,
    must_change_password: row.must_change_password,
    is_verified: true,
    is_sample: false,
    created_date: row.created_date instanceof Date ? row.created_date.toISOString() : row.created_date,
    updated_date: row.updated_date instanceof Date ? row.updated_date.toISOString() : row.updated_date,
    created_by: 'system',
    created_by_id: null,
  };
}

async function createSession(userId, societyId) {
  const token = crypto.randomBytes(32).toString('hex');
  await pool.query(
    `INSERT INTO sessions (id, user_id, society_id, token_hash, expires_at) VALUES ($1,$2,$3,$4,$5)`,
    [newId(), userId, societyId || null, sha256(token), new Date(Date.now() + SESSION_TTL_MS)]
  );
  return token;
}

async function pruneSessions() {
  await pool.query('DELETE FROM sessions WHERE expires_at <= now()');
}

async function resolveSession(token) {
  if (!token) return null;
  const { rows } = await pool.query(
    'SELECT * FROM sessions WHERE token_hash = $1 AND expires_at > now()',
    [sha256(token)]
  );
  const session = rows[0];
  if (!session) return null;

  if (!session.society_id) {
    const { rows: saRows } = await pool.query('SELECT * FROM superadmins WHERE id = $1', [session.user_id]);
    const sa = saRows[0];
    if (!sa || sa.disabled) return null;
    return { session, user: superadminRowToUser(sa), society: null, schemaName: null };
  }

  const society = await getSocietyById(session.society_id);
  if (!society) return null;
  const schemaName = await getSocietySchemaName(session.society_id);
  const user = await getEntityRecord(schemaName, 'User', session.user_id);
  if (!user || user.disabled) return null;
  return { session, user, society, schemaName };
}

function bearerToken(req) {
  const header = req.headers.authorization || '';
  if (header.toLowerCase().startsWith('bearer ')) return header.slice(7).trim();
  if (typeof req.query.token === 'string') return req.query.token; // EventSource cannot set headers
  return null;
}

async function requireAuth(req, res, next) {
  try {
    const resolved = await resolveSession(bearerToken(req));
    if (!resolved) return res.status(401).json({ message: 'Authentication required' });
    req.user = resolved.user;
    req.session = resolved.session;
    req.society = resolved.society;
    req.schemaName = resolved.schemaName;
    next();
  } catch (err) {
    next(err);
  }
}

function requireAdmin(req, res, next) {
  if (req.user?.role !== 'admin') return res.status(403).json({ message: 'Admin access required' });
  next();
}

function requireSuperadmin(req, res, next) {
  if (req.user?.role !== 'superadmin') return res.status(403).json({ message: 'Super admin access required' });
  next();
}

function requireSocietySchema(req, res, next) {
  if (!req.schemaName) return res.status(403).json({ message: 'Not available for super admin accounts' });
  next();
}

/* ------------------------------------------------------------------ */
/* Server-sent events (for entity.subscribe)                          */
/* ------------------------------------------------------------------ */

const sseClients = new Map(); // res -> schemaName

function broadcast(schemaName, entity, type, record) {
  if (sseClients.size === 0) return;
  const data = entity === 'User' ? publicUser(record) : record;
  const payload = `data: ${JSON.stringify({ entity, type, id: record.id, data, timestamp: nowIso() })}\n\n`;
    for (const [client, info] of sseClients) {
    if (info.schema === schemaName && canRead(info.user, entity, record)) client.write(payload);
  }
}

/* ------------------------------------------------------------------ */
/* In-memory query helpers (applied to rows fetched from Postgres)    */
/* ------------------------------------------------------------------ */

function matchesCondition(actual, condition) {
  if (condition && typeof condition === 'object' && !Array.isArray(condition)) {
    return Object.entries(condition).every(([op, expected]) => {
      switch (op) {
        case '$eq': return actual === expected;
        case '$ne': return actual !== expected;
        case '$in': return Array.isArray(expected) && expected.includes(actual);
        case '$nin': return Array.isArray(expected) && !expected.includes(actual);
        case '$gt': return actual > expected;
        case '$gte': return actual >= expected;
        case '$lt': return actual < expected;
        case '$lte': return actual <= expected;
        case '$exists': return (actual !== undefined && actual !== null) === Boolean(expected);
        case '$regex': {
          try { return new RegExp(expected, 'i').test(String(actual ?? '')); } catch { return false; }
        }
        default: return false;
      }
    });
  }
  if (Array.isArray(actual)) return actual.includes(condition);
  return actual === condition;
}

function matchesQuery(record, query) {
  if (!query || typeof query !== 'object') return true;
  return Object.entries(query).every(([field, condition]) => {
    if (field === '$or') return Array.isArray(condition) && condition.some((q) => matchesQuery(record, q));
    if (field === '$and') return Array.isArray(condition) && condition.every((q) => matchesQuery(record, q));
    return matchesCondition(record[field], condition);
  });
}

function sortRecords(records, sort) {
  if (!sort || typeof sort !== 'string') return records;
  const desc = sort.startsWith('-');
  const field = desc ? sort.slice(1) : sort;
  return [...records].sort((a, b) => {
    const av = a[field];
    const bv = b[field];
    if (av === bv) return 0;
    if (av === undefined || av === null) return 1;
    if (bv === undefined || bv === null) return -1;
    const cmp = av < bv ? -1 : 1;
    return desc ? -cmp : cmp;
  });
}

const clean = (entity, record) => (entity === 'User' ? publicUser(record) : record);

/* ------------------------------------------------------------------ */
/* App                                                                */
/* ------------------------------------------------------------------ */

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));

const wrap = (handler) => (req, res, next) => Promise.resolve(handler(req, res, next)).catch(next);

app.get('/api/health', wrap(async (_req, res) => {
  await pool.query('SELECT 1');
  res.json({ success: true, message: 'WGate backend is running', storage: 'postgres', time: nowIso() });
}));

app.get('/api/public-settings', (_req, res) => {
  res.json({ id: 'wgate-local', public_settings: { auth_mode: 'local', app_name: 'WGate' } });
});

app.get('/api/public/societies', wrap(async (_req, res) => {
  const societies = await listSocieties();
  res.json(societies.map(({ id, name, city, total_flats }) => ({ id, name, city, total_flats })));
}));

/* ---------------------------- auth ---------------------------- */

app.post('/api/auth/login', wrap(async (req, res) => {
  const email = normEmail(req.body?.email);
  const password = req.body?.password;
  const requestedSocietyId = req.body?.society_id || null;
  if (!email || !password) return res.status(400).json({ message: 'Email and password are required' });

  if (!requestedSocietyId) {
    // No society selected — this is the super admin login path.
    const { rows } = await pool.query('SELECT * FROM superadmins WHERE email = $1', [email]);
    const sa = rows[0];
    if (!sa || sa.disabled || !verifyPassword(password, sa.password_hash)) {
      return res.status(401).json({ message: 'Invalid email or password' });
    }
    await pruneSessions();
    const token = await createSession(sa.id, null);
    return res.json({ token, user: publicUser(superadminRowToUser(sa)) });
  }

  const society = await getSocietyById(requestedSocietyId);
  if (!society) return res.status(404).json({ message: 'Society not found' });
  const schemaName = await getSocietySchemaName(requestedSocietyId);

  const user = await findUserByEmail(schemaName, email);
  if (!user || user.disabled || !verifyPassword(password, user.password_hash)) {
    return res.status(401).json({ message: 'Invalid email or password' });
  }

  await pruneSessions();
  const token = await createSession(user.id, requestedSocietyId);
  res.json({ token, user: publicUser(user) });
}));

app.post('/api/auth/logout', wrap(async (req, res) => {
  const token = bearerToken(req);
  if (token) {
    await pool.query('DELETE FROM sessions WHERE token_hash = $1', [sha256(token)]);
  }
  res.json({ success: true });
}));

app.get('/api/auth/me', requireAuth, (req, res) => {
  res.json(publicUser(req.user));
});

app.patch('/api/auth/me', requireAuth, wrap(async (req, res) => {
  if (!req.schemaName) {
    // Super admin self-update — just full_name is editable here.
    if (req.body?.full_name !== undefined) {
      await pool.query('UPDATE superadmins SET full_name = $1, updated_date = now() WHERE id = $2', [req.body.full_name, req.user.id]);
    }
    const { rows } = await pool.query('SELECT * FROM superadmins WHERE id = $1', [req.user.id]);
    return res.json(publicUser(superadminRowToUser(rows[0])));
  }

  const patch = {};
  for (const key of SELF_EDITABLE_FIELDS) {
    if (req.body && Object.prototype.hasOwnProperty.call(req.body, key)) patch[key] = req.body[key];
  }
  const updated = { ...req.user, ...patch, updated_date: nowIso() };
  await updateEntityRecord(req.schemaName, 'User', updated.id, updated);
  broadcast(req.schemaName, 'User', 'update', updated);
  res.json(publicUser(updated));
}));

app.post('/api/auth/change-password', requireAuth, wrap(async (req, res) => {
  const { current_password: current, new_password: next } = req.body || {};
  if (!verifyPassword(current, req.user.password_hash)) {
    return res.status(400).json({ message: 'Current password is incorrect' });
  }
  if (!next || String(next).length < 6) {
    return res.status(400).json({ message: 'New password must be at least 6 characters' });
  }
  const newHash = hashPassword(next);

  if (!req.schemaName) {
    await pool.query(
      'UPDATE superadmins SET password_hash = $1, must_change_password = false, updated_date = now() WHERE id = $2',
      [newHash, req.user.id]
    );
    const { rows } = await pool.query('SELECT * FROM superadmins WHERE id = $1', [req.user.id]);
    return res.json({ success: true, user: publicUser(superadminRowToUser(rows[0])) });
  }

  const updated = { ...req.user, password_hash: newHash, must_change_password: false, updated_date: nowIso() };
  await updateEntityRecord(req.schemaName, 'User', updated.id, updated);
  res.json({ success: true, user: publicUser(updated) });
}));

/* Invite a member */
app.post('/api/users/invite', requireAuth, requireAdmin, requireSocietySchema, wrap(async (req, res) => {
  const email = normEmail(req.body?.email);
  if (!email) return res.status(400).json({ message: 'Email is required' });
  if (await findUserByEmail(req.schemaName, email)) {
    return res.status(409).json({ message: 'A user with this email already exists in this society' });
  }
  const requested = req.body?.role;
  const role = requested === 'admin' ? 'admin' : ROLES.includes(requested) ? requested : 'tenant';
  const user = {
    ...baseRecord({ created_by: req.user.email, created_by_id: req.user.id }),
    email,
    password_hash: hashPassword(DEFAULT_INVITE_PASSWORD),
    full_name: req.body?.full_name || email.split('@')[0],
    role,
    flat_number: req.body?.flat_number || '',
    phone: req.body?.phone || '',
    society_id: req.society.id,
    society_name: req.society.name,
    disabled: false,
    is_verified: false,
  };
  await insertEntityRecord(req.schemaName, 'User', user);
  broadcast(req.schemaName, 'User', 'create', user);
  res.status(201).json({ ...publicUser(user), initial_password: DEFAULT_INVITE_PASSWORD });
}));

/* ------------------------- super admin routes ------------------------- */
/* Only a 'superadmin' account can reach these: creating, editing and
   deleting societies (each backed by its own Postgres schema), creating
   admins for a society, and resetting an admin's password. */

app.post('/api/superadmin/societies', requireAuth, requireSuperadmin, wrap(async (req, res) => {
  const name = (req.body?.name || '').trim();
  if (!name) return res.status(400).json({ message: 'Society name is required' });
  const society = await createSocietyRecord({
    name,
    city: req.body?.city,
    address: req.body?.address,
    total_flats: req.body?.total_flats ?? null,
  });
  res.status(201).json(society);
}));

app.patch('/api/superadmin/societies/:id', requireAuth, requireSuperadmin, wrap(async (req, res) => {
  const existing = await getSocietyById(req.params.id);
  if (!existing) return res.status(404).json({ message: 'Society not found' });

  const patch = {};
  if (req.body?.name !== undefined) {
    const name = String(req.body.name).trim();
    if (!name) return res.status(400).json({ message: 'Society name is required' });
    patch.name = name;
  }
  if (req.body?.city !== undefined) patch.city = req.body.city;
  if (req.body?.address !== undefined) patch.address = req.body.address;
  if (req.body?.total_flats !== undefined) patch.total_flats = req.body.total_flats;

  const updated = await updateSocietyRecord(req.params.id, patch);

  // Keep the denormalized society_name in sync inside that society's own
  // schema, so renaming a society doesn't leave stale names on records.
  if (patch.name && patch.name !== existing.name) {
    const schemaName = await getSocietySchemaName(updated.id);
    for (const entity of ['User', 'Notice']) {
      const affected = await listEntity(schemaName, entity);
      for (const r of affected) {
        if (r.society_id === updated.id) {
          await updateEntityRecord(schemaName, entity, r.id, { ...r, society_name: updated.name, updated_date: nowIso() });
        }
      }
    }
  }

  res.json(updated);
}));

app.delete('/api/superadmin/societies/:id', requireAuth, requireSuperadmin, wrap(async (req, res) => {
  const society = await getSocietyById(req.params.id);
  if (!society) return res.status(404).json({ message: 'Society not found' });
  const schemaName = await getSocietySchemaName(society.id);
  const userCount = await countEntity(schemaName, 'User');
  if (userCount > 0) {
    return res.status(409).json({
      message: 'This society still has members. Remove them first before deleting the society.',
    });
  }
  await deleteSocietyRecord(society.id);
  res.json({ success: true });
}));

app.post('/api/superadmin/admins', requireAuth, requireSuperadmin, wrap(async (req, res) => {
  const email = normEmail(req.body?.email);
  if (!email) return res.status(400).json({ message: 'Email is required' });
  const society = await getSocietyById(req.body?.society_id);
  if (!society) return res.status(400).json({ message: 'Society is required' });
  const schemaName = await getSocietySchemaName(society.id);

  if (await findUserByEmail(schemaName, email)) {
    return res.status(409).json({ message: 'A user with this email already exists in this society' });
  }

  const adminUser = {
    ...baseRecord({ created_by: req.user.email, created_by_id: req.user.id }),
    email,
    password_hash: hashPassword(DEFAULT_INVITE_PASSWORD),
    full_name: req.body?.full_name || email.split('@')[0],
    role: 'admin',
    flat_number: req.body?.flat_number || '',
    phone: req.body?.phone || '',
    society_id: society.id,
    society_name: society.name,
    disabled: false,
    is_verified: false,
    must_change_password: true,
  };
  await insertEntityRecord(schemaName, 'User', adminUser);
  res.status(201).json({ ...publicUser(adminUser), initial_password: DEFAULT_INVITE_PASSWORD });
}));

app.get('/api/superadmin/societies', requireAuth, requireSuperadmin, wrap(async (_req, res) => {
  const societies = await listSocieties();
  const withAdmins = await Promise.all(societies.map(async (s) => {
    const schemaName = await getSocietySchemaName(s.id);
    const users = await listEntity(schemaName, 'User');
    const admins = users
      .filter((u) => u.role === 'admin')
      .map(publicUser)
      .sort((a, b) => a.full_name.localeCompare(b.full_name));
    return { ...s, admins };
  }));
  res.json(withAdmins.sort((a, b) => a.name.localeCompare(b.name)));
}));

app.post('/api/superadmin/admins/:id/reset-password', requireAuth, requireSuperadmin, wrap(async (req, res) => {
  const society = await getSocietyById(req.body?.society_id);
  if (!society) return res.status(400).json({ message: 'Society is required' });
  const schemaName = await getSocietySchemaName(society.id);

  const target = await getEntityRecord(schemaName, 'User', req.params.id);
  if (!target) return res.status(404).json({ message: 'Admin not found' });
  if (target.role !== 'admin') return res.status(400).json({ message: 'This action is only available for society admins' });

  const tempPassword = generateTempPassword();
  const updated = {
    ...target,
    password_hash: hashPassword(tempPassword),
    must_change_password: true,
    updated_date: nowIso(),
  };
  await updateEntityRecord(schemaName, 'User', updated.id, updated);
  await pool.query('DELETE FROM sessions WHERE user_id = $1', [updated.id]);

  res.json({ email: updated.email, password: tempPassword });
}));

/* Distinct resident flat numbers — used by the guard's visitor check-in
   form to pick a flat instead of typing it freehand. Open to any
   authenticated role (not just admin), but only returns flat numbers,
   not full user records, so it doesn't leak other residents' PII. */
app.get('/api/flats', requireAuth, requireSocietySchema, wrap(async (req, res) => {
  const { rows } = await pool.query(`
    SELECT DISTINCT data->>'flat_number' AS flat_number
    FROM "${req.schemaName}".entity_records
    WHERE entity = 'User'
      AND data->>'role' IN ('tenant', 'owner')
      AND data->>'flat_number' <> ''
    ORDER BY flat_number
  `);
  res.json(rows.map((r) => r.flat_number));
}));

/* ------------------------- realtime events ------------------------- */

app.get('/api/events', requireAuth, requireSocietySchema, (req, res) => {
  res.set({
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache, no-transform',
    Connection: 'keep-alive',
    'X-Accel-Buffering': 'no',
  });
  res.flushHeaders?.();
  res.write('retry: 2000\n\n');
  sseClients.set(res, { schema: req.schemaName, user: req.user });
  const heartbeat = setInterval(() => res.write(': ping\n\n'), 25000);
  req.on('close', () => {
    clearInterval(heartbeat);
    sseClients.delete(res);
  });
});

/* --------------------------- entities --------------------------- */

const entityRouter = express.Router();
entityRouter.use(requireAuth);
entityRouter.use(requireSocietySchema);

entityRouter.use('/:name', (req, res, next) => {
  if (!ENTITIES.includes(req.params.name)) {
    return res.status(404).json({ message: `Unknown entity: ${req.params.name}` });
  }
  next();
});

function assertUserWriteAllowed(req, res) {
  /* ------------------------------------------------------------------ */
/* Access rules: who may read / write what                            */
/* Enforced here on the server, so they can't be bypassed from the   */
/* browser. They mirror what each screen already allows.             */
/* ------------------------------------------------------------------ */

const isStaff = (u) => u.role === 'admin' || u.role === 'guard';
const isResident = (u) => u.role === 'tenant' || u.role === 'owner';
const flatKey = (v) => String(v ?? '').trim().toLowerCase();
const sameFlat = (u, r) => !!flatKey(u.flat_number) && flatKey(u.flat_number) === flatKey(r.flat_number);
const sameEmail = (u, r) => !!u.email && !!r.resident_email && normEmail(u.email) === normEmail(r.resident_email);

// Who may create / edit / delete each entity. Visitor and ServiceTicket have
// finer rules in authorizeCreate / authorizeUpdate below.
// Notice includes guards because the Notice Board screen lets them post.
const WRITE_ROLES = {
  User: ['admin'],
  SocietySettings: ['admin'],
  MaintenanceBill: ['admin'],
  Notice: ['admin', 'guard'],
};

function canRead(user, entity, record) {
  switch (entity) {
    case 'User': return user.role === 'admin' || record.id === user.id;
    case 'SocietySettings':
    case 'Notice': return true;
    case 'Visitor': return isStaff(user) || sameFlat(user, record);
    case 'ServiceTicket': return isStaff(user) || sameEmail(user, record);
    case 'MaintenanceBill': return user.role === 'admin' || sameFlat(user, record) || sameEmail(user, record);
    default: return false;
  }
}

function canDelete(user, entity) {
  return (WRITE_ROLES[entity] || ['admin']).includes(user.role);
}

const denyWrite = (res, message = 'You do not have permission to do that') => {
  res.status(403).json({ message });
  return null;
};

const pickDefined = (obj, keys) =>
  Object.fromEntries(keys.filter((k) => obj[k] !== undefined).map((k) => [k, obj[k]]));

// Returns the record input to store (sanitized), or null after sending a 403.
function authorizeCreate(req, res, entity, input) {
  const user = req.user;
  const body = input && typeof input === 'object' && !Array.isArray(input) ? { ...input } : {};
  if (WRITE_ROLES[entity]) {
    return WRITE_ROLES[entity].includes(user.role) ? body : denyWrite(res);
  }
  if (entity === 'Visitor') {
    if (user.role === 'admin') return body;
    if (user.role !== 'guard') return denyWrite(res, 'Only security and admins can check in visitors');
    delete body.check_out_time;
    body.status = 'pending'; // guards cannot pre-approve their own check-ins
    return body;
  }
  if (entity === 'ServiceTicket') {
    if (user.role === 'admin') return body;
    if (!isResident(user)) return denyWrite(res, 'Only residents and admins can raise tickets');
    return {
      ...pickDefined(body, ['title', 'description', 'category', 'priority']),
      flat_number: user.flat_number || body.flat_number,
      resident_email: user.email, // always the signed-in resident, never someone else
      status: 'open',
    };
  }
  return denyWrite(res);
}

// Returns the patch to apply (sanitized), or null after sending a 403.
function authorizeUpdate(req, res, entity, record, patch) {
  const user = req.user;
  const body = patch && typeof patch === 'object' && !Array.isArray(patch) ? { ...patch } : {};
  if (WRITE_ROLES[entity]) {
    return WRITE_ROLES[entity].includes(user.role) ? body : denyWrite(res);
  }
  if (entity === 'ServiceTicket') {
    return user.role === 'admin' ? body : denyWrite(res, 'Only admins can update tickets');
  }
  if (entity === 'Visitor') {
    if (user.role === 'admin') return body;
    const keys = Object.keys(body);
    if (user.role === 'guard') {
      const onlyCheckout = keys.length > 0 && keys.every((k) => k === 'check_out_time');
      return record.status === 'approved' && onlyCheckout
        ? body
        : denyWrite(res, 'Security can only check out approved visitors');
    }
    if (isResident(user) && sameFlat(user, record)) {
      const onlyDecision = keys.length === 1 && keys[0] === 'status' && ['approved', 'rejected'].includes(body.status);
      return onlyDecision ? body : denyWrite(res, 'You can only approve or reject visitors for your flat');
    }
    return denyWrite(res);
  }
  return denyWrite(res);
}

const enforceEntityAccess = wrap(async (req, res, next) => {
  const entity = req.params.name;
  const [first] = req.path.split('/').filter(Boolean); // undefined | 'bulk' | <record id>

  if (req.method === 'POST') {
    if (first === 'bulk') {
      const items = Array.isArray(req.body) ? req.body : req.body?.items;
      if (!Array.isArray(items)) return next(); // the route itself returns the 400
      const allowed = [];
      for (const item of items) {
        const input = authorizeCreate(req, res, entity, item);
        if (!input) return; // 403 already sent
        allowed.push(input);
      }
      req.body = allowed;
      return next();
    }
    const input = authorizeCreate(req, res, entity, req.body);
    if (!input) return;
    req.body = input;
    return next();
  }

  if (first && ['PUT', 'PATCH', 'DELETE'].includes(req.method)) {
    const record = await getEntityRecord(req.schemaName, entity, first);
    if (!record) return next(); // the route itself returns the 404
    if (req.method === 'DELETE') {
      if (!canDelete(req.user, entity)) return denyWrite(res, 'You do not have permission to delete this');
      return next();
    }
    const patch = authorizeUpdate(req, res, entity, record, req.body);
    if (!patch) return;
    req.body = patch;
  }
  next();
});
entityRouter.use('/:name', enforceEntityAccess);
  if (req.params.name === 'User' && req.user.role !== 'admin') {
    res.status(403).json({ message: 'Only admins can manage users' });
    return false;
  }
  return true;
}

async function buildRecord(schemaName, entity, input, actor, activeSociety) {
  const record = {
    ...(ENTITY_DEFAULTS[entity] || {}),
    ...input,
    id: newId(),
    created_date: nowIso(),
    updated_date: nowIso(),
    created_by: actor.email,
    created_by_id: actor.id,
    is_sample: false,
  };
  if (entity === 'User') {
    if (record.role === 'superadmin') {
      throw Object.assign(new Error('Super admin accounts cannot be created this way'), { status: 403 });
    }
    record.email = normEmail(record.email);
    if (!record.email) throw Object.assign(new Error('Email is required'), { status: 400 });
    if (await findUserByEmail(schemaName, record.email)) {
      throw Object.assign(new Error('A user with this email already exists'), { status: 409 });
    }
    record.society_id = activeSociety.id;
    record.society_name = activeSociety.name;
    record.password_hash = hashPassword(record.password || DEFAULT_INVITE_PASSWORD);
    delete record.password;
  }
  if (entity === 'Notice' || entity === 'SocietySettings') {
    record.society_id = activeSociety.id;
    record.society_name = activeSociety.name;
  }
  return record;
}

entityRouter.get('/:name', wrap(async (req, res) => {
  const entity = req.params.name;
  let query = {};
  if (req.query.q) {
    try { query = JSON.parse(String(req.query.q)); } catch { return res.status(400).json({ message: 'Invalid q parameter' }); }
  }
  let rows = await listEntity(req.schemaName, entity);
  if (entity === 'User' && req.user.role !== 'admin') {
    rows = rows.filter((r) => canRead(req.user, entity, r));
  }
  rows = rows.filter((r) => matchesQuery(r, query));
  rows = sortRecords(rows, req.query.sort ? String(req.query.sort) : '-created_date');
  const skip = Math.max(0, parseInt(req.query.skip, 10) || 0);
  const limit = parseInt(req.query.limit, 10);
  rows = rows.slice(skip, Number.isFinite(limit) && limit > 0 ? skip + limit : undefined);
  res.json(rows.map((r) => clean(entity, r)));
}));

entityRouter.get('/:name/:id', wrap(async (req, res) => {
  const entity = req.params.name;
  const record = await getEntityRecord(req.schemaName, entity, req.params.id);
  if (!record) return res.status(404).json({ message: `${entity} not found` });
    if (!canRead(req.user, entity, record)) return res.status(404).json({ message: `${entity} not found` });
  res.json(clean(entity, record));
}));

entityRouter.post('/:name/bulk', wrap(async (req, res) => {
  if (!assertUserWriteAllowed(req, res)) return;
  const entity = req.params.name;
  const items = Array.isArray(req.body) ? req.body : req.body?.items;
  if (!Array.isArray(items)) return res.status(400).json({ message: 'Expected an array' });
  try {
    const created = [];
    for (const item of items) {
      const record = await buildRecord(req.schemaName, entity, item || {}, req.user, req.society);
      await insertEntityRecord(req.schemaName, entity, record);
      created.push(record);
    }
    created.forEach((r) => broadcast(req.schemaName, entity, 'create', r));
    res.status(201).json(created.map((r) => clean(entity, r)));
  } catch (err) {
    res.status(err.status || 400).json({ message: err.message });
  }
}));

entityRouter.post('/:name', wrap(async (req, res) => {
  if (!assertUserWriteAllowed(req, res)) return;
  const entity = req.params.name;
  try {
    const record = await buildRecord(req.schemaName, entity, req.body || {}, req.user, req.society);
    await insertEntityRecord(req.schemaName, entity, record);
    broadcast(req.schemaName, entity, 'create', record);
    res.status(201).json(clean(entity, record));
  } catch (err) {
    res.status(err.status || 400).json({ message: err.message });
  }
}));

async function updateHandler(req, res) {
  if (!assertUserWriteAllowed(req, res)) return;
  const entity = req.params.name;
  const record = await getEntityRecord(req.schemaName, entity, req.params.id);
  if (!record) return res.status(404).json({ message: `${entity} not found` });

  const patch = { ...(req.body || {}) };
  delete patch.id;
  delete patch.created_date;
  delete patch.created_by;
  delete patch.created_by_id;
  delete patch.password_hash;
  delete patch.society_id;
  delete patch.society_name;

  if (entity === 'User') {
    if (patch.email !== undefined) {
      patch.email = normEmail(patch.email);
      const existing = await findUserByEmail(req.schemaName, patch.email);
      if (existing && existing.id !== record.id) {
        return res.status(409).json({ message: 'A user with this email already exists' });
      }
    }
    if (patch.password) {
      patch.password_hash = hashPassword(patch.password);
    }
    delete patch.password;
    if (patch.role !== undefined && !ROLES.includes(patch.role)) {
      return res.status(400).json({ message: `Invalid role. Use one of: ${ROLES.join(', ')}` });
    }
    if (record.id === req.user.id && patch.role && patch.role !== 'admin') {
      return res.status(400).json({ message: 'You cannot remove your own admin role' });
    }
  }

  const updated = { ...record, ...patch, updated_date: nowIso() };
  await updateEntityRecord(req.schemaName, entity, req.params.id, updated);
  broadcast(req.schemaName, entity, 'update', updated);
  res.json(clean(entity, updated));
}
entityRouter.put('/:name/:id', wrap(updateHandler));
entityRouter.patch('/:name/:id', wrap(updateHandler));

entityRouter.delete('/:name/:id', wrap(async (req, res) => {
  if (!assertUserWriteAllowed(req, res)) return;
  const entity = req.params.name;
  const record = await getEntityRecord(req.schemaName, entity, req.params.id);
  if (!record) return res.status(404).json({ message: `${entity} not found` });
  if (entity === 'User' && record.id === req.user.id) {
    return res.status(400).json({ message: 'You cannot delete your own account' });
  }
  await deleteEntityRecord(req.schemaName, entity, req.params.id);
  if (entity === 'User') {
    await pool.query('DELETE FROM sessions WHERE user_id = $1', [record.id]);
  }
  broadcast(req.schemaName, entity, 'delete', record);
  res.json({ success: true });
}));

app.use('/api/entities', entityRouter);

app.use('/api', (_req, res) => res.status(404).json({ message: 'Not found' }));

// eslint-disable-next-line no-unused-vars
app.use((err, _req, res, _next) => {
  console.error('[wgate-api] Unhandled error:', err);
  res.status(err.status || 500).json({ message: err.message || 'Internal server error' });
});

/* ------------------------------------------------------------------ */
/* Boot                                                               */
/* ------------------------------------------------------------------ */

async function main() {
  await initSchema();
  await seedIfEmpty();
  await pruneSessions();

  const server = app.listen(PORT, HOST, () => {
    console.log(`[wgate-api] Backend running at http://${HOST}:${PORT} (Postgres, schema-per-society)`);
  });

  server.on('error', (err) => {
    if (err.code === 'EADDRINUSE') {
      console.error(`[wgate-api] Port ${PORT} is already in use. Close the other process or set WGATE_API_PORT.`);
    } else {
      console.error('[wgate-api] Server error:', err);
    }
    process.exit(1);
  });
}

main().catch((err) => {
  console.error('[wgate-api] Failed to start:', err.message);
  process.exit(1);
});
